import NumBox from "@/components/atoms/NumBox";
import StatsBox from "@/components/atoms/StatsBox";
import { ChevronRightIcon } from "@chakra-ui/icons";
import {
  Box,
  Button,
  Divider,
  Flex,
  Grid,
  GridItem,
  Stack,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <Box bg={"#FBFCFC"} h={"100vh"} w={"100vw"} className="container-main">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Box w="auto" display={"flex"} pt={5} gap={2} alignItems={"center"}>
        <Image src="/assests/handIcon.svg" width={30} height={30} />
        <Text fontSize={"large"} fontWeight={600} color={"#191919"}>
          Hi Ahmed
        </Text>
      </Box>
      <Text fontSize={"xs"} fontWeight={400} color={"#3D3D3D"} mt={2}>
        Welcome to your Dashboard
      </Text>

      <Flex mt={10} gap={5} justifyContent={"space-between"}>
        <Box
          w={856}
          h={325}
          borderRadius={16}
          bg="white"
          boxShadow={"0px 4px 8px 0px rgba(0, 0, 0, 0.02)"}
        >
          <Flex p={4}>
            <Box w="100%">
              <Text fontWeight={600} fontSize="large">
                Sales Overview
              </Text>
              <Text color={"#606060"} fontSize="xs">
                Showing overview Jan 2022 - Sep 2022
              </Text>
            </Box>
            <Button
              size="md"
              height="46px"
              width="177px"
              border="1px"
              borderColor="#CBCBCB"
              bg={"transparent"}
              fontWeight={500}
              fontSize="xs"
              color={"#CBCBCB"}
            >
              View Transactions
            </Button>
          </Flex>
          <Tabs align="end" variant="soft-rounded" defaultIndex={2}>
            <TabList pr={4}>
              <Tab
                _selected={{
                  color: "black",
                  bg: "#f5f5f5",
                  fontWeight: 600,
                  borderRadius: 8,
                }}
                fontWeight={500}
              >
                1 Week
              </Tab>
              <Tab
                _selected={{
                  color: "black",
                  bg: "#f5f5f5",
                  fontWeight: 600,
                  borderRadius: 8,
                }}
                fontWeight={500}
              >
                1 month
              </Tab>
              <Tab
                _selected={{
                  color: "black",
                  bg: "#f5f5f5",
                  fontWeight: 600,
                  borderRadius: 8,
                }}
                fontWeight={500}
              >
                1 Year
              </Tab>
            </TabList>
            <Divider mt={2} />
            <TabPanels>
              <TabPanel>
                <p>one!</p>
              </TabPanel>
              <TabPanel>
                <p>two!</p>
              </TabPanel>
              <TabPanel>
                <Flex gap={5}>
                  <Box border={"2px solid #f5f5f5"} w="50%"></Box>
                  <Grid templateColumns="repeat(2, 1fr)" gap={4}>
                    <GridItem>
                      <NumBox
                        name={"Balance"}
                        color={"#4545FE"}
                        direction="increase"
                      />
                    </GridItem>
                    <GridItem>
                      <NumBox
                        name={"Deposit"}
                        color={"#12D8A0"}
                        direction="increase"
                      />
                    </GridItem>
                    <GridItem>
                      <NumBox
                        name={"Purchase"}
                        color={"#191919"}
                        direction="increase"
                      />
                    </GridItem>
                    <GridItem>
                      <NumBox
                        name={"Withdrawal"}
                        color={"#FF6A6A"}
                        direction="decrease"
                      />
                    </GridItem>
                  </Grid>
                </Flex>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>
        <Stack>
          <Box
            w={407}
            h={157}
            borderRadius={16}
            bg="white"
            boxShadow={"0px 4px 8px 0px rgba(0, 0, 0, 0.02)"}
            p={3}
          >
            <Flex justifyContent={"space-between"}>
              <Text
                display={"flex"}
                gap={2}
                color="#3d3d3d"
                fontWeight={500}
                alignItems="center"
              >
                <Image src="/assests/propertyIcon.svg" width={20} height={20} />
                Property Overview
              </Text>
              <Button
                bg="transparent"
                _hover={{ bg: "transparent" }}
                fontWeight={500}
                fontSize="xs"
                color={"#cbcbcb"}
              >
                View all
                <ChevronRightIcon fontSize={"md"} />
              </Button>
            </Flex>
            <Grid templateColumns="repeat(3, 1fr)" gap={3} mt={2}>
              <GridItem>
                <StatsBox name={"Total"} />
              </GridItem>
              <GridItem>
                <StatsBox name={"Available"} />
              </GridItem>
              <GridItem>
                <StatsBox name={"Sold Out"} />
              </GridItem>
            </Grid>
          </Box>
          <Box
            w={407}
            h={157}
            borderRadius={16}
            bg="white"
            boxShadow={"0px 4px 8px 0px rgba(0, 0, 0, 0.02)"}
            p={3}
          >
            <Flex justifyContent={"space-between"}>
              <Text
                display={"flex"}
                gap={2}
                color="#3d3d3d"
                fontWeight={500}
                alignItems="center"
              >
                <Image src="/assests/profileIcon.svg" width={25} height={20} />
                Customers Overview
              </Text>
              <Button
                bg="transparent"
                _hover={{ bg: "transparent" }}
                fontWeight={500}
                fontSize="xs"
                color={"#cbcbcb"}
              >
                View all
                <ChevronRightIcon fontSize={"md"} />
              </Button>
            </Flex>
            <Grid templateColumns="repeat(4, 1fr)" gap={2} mt={2}>
              <GridItem>
                <StatsBox small name={"Total"} />
              </GridItem>
              <GridItem>
                <StatsBox small name={"New"} />
              </GridItem>
              <GridItem>
                <StatsBox small name={"Active"} />
              </GridItem>
              <GridItem>
                <StatsBox small name={"Inactive"} />
              </GridItem>
            </Grid>
          </Box>
        </Stack>
      </Flex>
    </Box>
  );
}
